### ISSUE TITLE
タスクと情報収集

### ISSUE THREAD

**Issue by shunya28** [pamiyummy/Demo_MusicPlayingTool#1]
### 盛り込みたい機能
- [x] 画面をクリックしたら音が鳴るようにする
- [ ] 画面上に図形を作る
- [ ] 図形をクリックしたら音が鳴るようにする
- [ ] 図形の上をドラッグしたら音が鳴るようにする
- [ ] 複数の図形を作成して、それぞれの図形をクリックすると別の音が鳴るようにする
  - [ ] 図形の上をドラッグしたときにも、別々に音が鳴るようにする

**Comment by shunya28** [comment]
### 音を鳴らすコード
引用：[Java 音声ファイルを再生して音を鳴らす、ビープ音を鳴らす](https://www.javalife.jp/2018/01/07/post-280/)
```
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioFileFormat.Type;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
 
public class MP3Player {
    public static void main(String[] args) {
 
        System.out.println("===== サポートしている形式 =====");
        Type[] typeArray = AudioSystem.getAudioFileTypes();
        for(Type type : typeArray) {
            System.out.println(type.toString());
        }
 
        AudioInputStream ais = null;
        try {
            ais = AudioSystem.getAudioInputStream(new File("../../data/Mixdown.wav"));
            AudioFormat af = ais.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, af);
            Clip clip = (Clip)AudioSystem.getLine(info);
            clip.open(ais);
            clip.loop(0);
            clip.flush();
            while(clip.isActive()) {
                Thread.sleep(100);
            }
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException | InterruptedException e) {
            e.printStackTrace();
        }finally {
            try {
                ais.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```
ちゃんと鳴った。ただし、WAVファイルによっては再生できないものもあるらしく、その場合下のようなエラーが出る。
```
Exception in thread "main" java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_FLOAT 44100.0 Hz, 32 bit, stereo, 8 bytes/frame is supported.
        at java.desktop/javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:425)
        at MP3Player.main(MP3Player.java:26)
```

**Comment by shunya28** [comment]
### 参考になりそうなサイト
- [外国語としてのJavaと音楽](https://mocha-java.com/page/12/?s=Java)
- 対応フォーマットは8bitか16bitらしい（[公式 Java Sound Technology](https://docs.oracle.com/javase/jp/8/docs/technotes/guides/sound/)）
  - 上のページのリファレンスを読んでおきたい
#### Basic Layer APIを使うとmp3も再生できるらしい
- [SwingとjavazoomのBasicPlayer APIを使用した超簡易プレイヤー](http://yasshiemd.web.fc2.com/sub/appli/simpleplayer/simpleplayer.html)
- [JavaでRAW,WAV,MP3ファイルを再生](https://qiita.com/hexaforce/items/a02a178edf811cfbaf34#mp3)

**Comment by shunya28** [comment]
[wavファイルからデータを取り込む方法](https://mocha-java.com/display-wav-1/)
[wavファイルを作成する方法](https://mocha-java.com/create-square-wave-1/)

**Comment by shunya28** [comment]
例外処理について
[参考サイト](https://qiita.com/pitan109/items/c9910edddc007126df41)
